SPREADSHEET_ID = "1EPY4FXw_K87VMz0MpMEFh5JWgdLMilBnudYXqhMr2-g"

JOB_RANGE = "House_Jobs!A2:G256"
POINT_RANGE = "Week_Scores!A1:F256"
NICKNAME_RANGE = "Nicknames"

SIGNOFF_BASE_POINTS = 1
SIGNOFF_ADD_POINTS = 1
SIGNOFF_LATE_AMOUNT = 0.5
SIGNOFF_ASSHO_POINTS = 0.1
SIGNOFF_NOT_DONE_STRING = "E-SIGNOFF"